<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><EnableDynamicLoading>true</EnableDynamicLoading></PropertyGroup><ItemGroup><ProjectReference Include="../MYSync.Provider.Abstractions/MYSync.Provider.Abstractions.csproj"/><None Include="plugin.json" CopyToOutputDirectory="PreserveNewest"/></ItemGroup></Project>
