<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../MYSync.Sync.Core/MYSync.Sync.Core.csproj" /><PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" /><PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" /></ItemGroup></Project>
